### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'asPoint'


### ISSUE THREAD

**Issue by Leshy2020** [IZSVenezie/VetEpiGIS-Tool#1]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/lordg\.config\\NextGIS\qgis2\python/plugins\VetEpiGIS-Tool\vetepigis_tool.py", line 1839, in createBuffers
    utm = self.getUTMzone(feat, psrid)
  File "C:/Users/lordg\.config\\NextGIS\qgis2\python/plugins\VetEpiGIS-Tool\vetepigis_tool.py", line 1912, in getUTMzone
    pt = geom.asPoint()
AttributeError: 'NoneType' object has no attribute 'asPoint'

```
VetEpiGIS-Tool 0.794, QGIS 2.18.28-Las Palmas on Windows 10

**Comment by mmazzucato** [comment]
@Chelahov we began the migration to QGIS 3. This issue will be solved for that version.

Keep in touch for news on that.

**Comment by mmazzucato** [comment]
Fixed.
